
import { useState } from 'react';
import MainNav from "@/components/layout/MainNav";
import Footer from "@/components/layout/Footer";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const About = () => {
  const [activeTab, setActiveTab] = useState("mission");

  return (
    <div className="min-h-screen flex flex-col">
      <MainNav />

      <main className="flex-grow container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-semibold mb-4">About HalalChat AI</h1>
            <p className="text-lg text-muted-foreground">
              Creating Halal content with peace of mind
            </p>
          </div>

          <Tabs
            defaultValue="mission"
            value={activeTab}
            onValueChange={setActiveTab}
            className="w-full"
          >
            <TabsList className="grid w-full grid-cols-3 mb-8">
              <TabsTrigger value="mission">Our Mission</TabsTrigger>
              <TabsTrigger value="values">Our Values</TabsTrigger>
              <TabsTrigger value="team">Our Team</TabsTrigger>
            </TabsList>

            <TabsContent value="mission" className="space-y-6">
              <div className="prose max-w-none">
                <h2 className="text-2xl font-medium mb-4">Our Mission</h2>
                <p className="mb-4">
                  HalalChat AI was founded with a clear mission: to provide Muslims and those seeking ethical content with an AI assistant that aligns with Islamic principles and values.
                </p>
                <p className="mb-4">
                  In today's digital world, many AI tools are trained on data that may include content contradicting Islamic values. We recognized this gap and created HalalChat AI to offer a solution that ensures all generated content respects Islamic guidelines and principles.
                </p>
                <p className="mb-4">
                  We believe that technology should serve humanity while respecting moral and ethical boundaries. Our mission is to make AI accessible for Muslims worldwide while maintaining the highest standards of ethical content creation.
                </p>
                <p>
                  HalalChat AI is committed to continuous improvement, learning, and adaptation to ensure that our service always meets the needs of our community while staying true to Islamic principles.
                </p>
              </div>
            </TabsContent>

            <TabsContent value="values" className="space-y-6">
              <div className="prose max-w-none">
                <h2 className="text-2xl font-medium mb-4">Our Core Values</h2>
                
                <div className="grid md:grid-cols-2 gap-6 mt-8">
                  <div className="bg-card p-6 rounded-lg border border-border">
                    <h3 className="text-xl font-medium mb-2 text-primary">Islamic Compliance</h3>
                    <p>
                      We ensure all content generated by our AI adheres to Islamic principles, avoiding anything that contradicts Islamic teachings.
                    </p>
                  </div>
                  
                  <div className="bg-card p-6 rounded-lg border border-border">
                    <h3 className="text-xl font-medium mb-2 text-primary">Ethical Technology</h3>
                    <p>
                      We believe in using technology to promote good and prevent harm, in line with Islamic teachings about responsible stewardship.
                    </p>
                  </div>
                  
                  <div className="bg-card p-6 rounded-lg border border-border">
                    <h3 className="text-xl font-medium mb-2 text-primary">Community-Focused</h3>
                    <p>
                      We prioritize building tools that serve the Muslim community's specific needs, creating a safe space for ethical content creation.
                    </p>
                  </div>
                  
                  <div className="bg-card p-6 rounded-lg border border-border">
                    <h3 className="text-xl font-medium mb-2 text-primary">Transparency</h3>
                    <p>
                      We are open about how our AI works, what data it uses, and how we ensure content remains halal and ethically sourced.
                    </p>
                  </div>
                </div>
              </div>
            </TabsContent>

            <TabsContent value="team" className="space-y-6">
              <div className="prose max-w-none">
                <h2 className="text-2xl font-medium mb-4">Our Team</h2>
                <p className="mb-6">
                  HalalChat AI is built by a diverse team of Muslims passionate about technology, ethics, and Islamic values. Our team includes:
                </p>
                
                <div className="grid md:grid-cols-3 gap-6">
                  <div className="text-center">
                    <div className="w-32 h-32 bg-accent rounded-full mx-auto mb-4 flex items-center justify-center">
                      <span className="text-4xl">👨‍💻</span>
                    </div>
                    <h3 className="text-lg font-medium">AI Engineers</h3>
                    <p className="text-sm text-muted-foreground">
                      Who ensure our models meet Islamic guidelines
                    </p>
                  </div>
                  
                  <div className="text-center">
                    <div className="w-32 h-32 bg-accent rounded-full mx-auto mb-4 flex items-center justify-center">
                      <span className="text-4xl">📚</span>
                    </div>
                    <h3 className="text-lg font-medium">Islamic Scholars</h3>
                    <p className="text-sm text-muted-foreground">
                      Who review content policies and provide guidance
                    </p>
                  </div>
                  
                  <div className="text-center">
                    <div className="w-32 h-32 bg-accent rounded-full mx-auto mb-4 flex items-center justify-center">
                      <span className="text-4xl">🌐</span>
                    </div>
                    <h3 className="text-lg font-medium">Community Managers</h3>
                    <p className="text-sm text-muted-foreground">
                      Who ensure we meet the needs of Muslims worldwide
                    </p>
                  </div>
                </div>
                
                <p className="mt-8">
                  Together, we work to create a platform that Muslims can trust for generating content that aligns with their values and beliefs.
                </p>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default About;
